# =====================================================
#  Playbook: deploy.yml
#  Scope   : Provision a fresh EC2 host, install/upgrade Minikube,
#            clone the private repo, apply Kubernetes manifests,
#            and expose selected services via port‑forward.
#            Requires:
#              • SSH key (SECRET_SSH_KEY) for the host (handled by GH Actions)
#              • GH_PAT env var with a Personal Access Token (scope: repo)
# =====================================================

- name: Deploy WasteVision_-_Evaluation on EC2 Minikube
  hosts: productEC2
  become: true
  vars:
    project_dir: /home/ec2-user/WasteVision_-_Evaluation/WasteVision
    repo_url: "https://github.com/RaffaeleCali/WasteVision_-_Evaluation.git" 
    repo_branch: main
    manifests_dir: "{{ project_dir }}/deployment"
    port_forward_specs:
      - svc: ollama
        local: 11434
        remote: 11434
      - svc: server
        local: 5000
        remote: 5000
      - svc: react-frontend
        local: 80
        remote: 80
      - svc: jaeger
        local: 31661
        remote: 16686

  tasks:

    - name: Ensure Git is installed
      package:
        name: git
        state: present

    - name: Ensure Docker group exists & ec2-user in it
      group:
        name: docker
        state: present
      register: docker_group

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
      when: docker_group.changed

    # -------------------------------------------------
    #  Project checkout
    # -------------------------------------------------
    
    # -------------------------------------------------
    #  Minikube installation (if missing)
    # -------------------------------------------------
    - name: Install kubectl if Minikube not found
      shell: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
      when: minikube_cli.rc != 0
      become: true

    - name: Install Docker if Minikube not found
      shell: |
        sudo yum update -y
        sudo yum install -y docker
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker ec2-user
      when: minikube_cli.rc != 0
      become: true

    - name: Install Minikube
      shell: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/minikube
      when: minikube_cli.rc != 0
      become: true

    # -------------------------------------------------
    #  Ensure Minikube is stopped & cleaned (fresh cluster)
    # -------------------------------------------------
    - name: Stop Minikube if running
      shell: minikube stop || true
      become: false
      when: minikube_cli.rc == 0
      ignore_errors: yes

    - name: Delete Minikube if existing
      shell: minikube delete || true
      become: false
      when: minikube_cli.rc == 0
      ignore_errors: yes

    # -------------------------------------------------
    #  Start Minikube (Docker driver, GPU optional)
    # -------------------------------------------------
    - name: Start Minikube (Docker driver)
      shell: |
        minikube start \
          --driver=docker \
          --memory=2827mb \
          --cpus=2 \
          --container-runtime=containerd \
          --addons=ingress
      args:
        executable: /bin/bash
      become: false

    # -------------------------------------------------
    #  Apply Kubernetes manifests
    # -------------------------------------------------
    - name: Apply only the namespace manifest
      shell: |
        kubectl apply -f {{ manifests_dir }}/namespace.yaml
      args:
        executable: /bin/bash
      become: false

    - name: Wait for namespace to exist
      shell: |
        for i in {1..10}; do
          kubectl get ns wastevsion && exit 0
          sleep 2
        done
        echo "Namespace not found" >&2
        exit 1
      args:
        executable: /bin/bash
      become: false

    - name: Apply remaining manifests
      shell: |
        find {{ manifests_dir }} -type f ! -name 'namespace.yaml' -exec kubectl apply -f {} \;
      args:
        executable: /bin/bash
      become: false


    - name: Wait until all pods are Running
      shell: |
        set -euo pipefail
        echo "Waiting for pods…";
        kubectl wait --for=condition=Ready pods --all -n wastevsion --timeout=300s
      args:
        executable: /bin/bash
      become: false

    