# =====================================================
#  React Front-End
# =====================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: wastevsion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: raffa8/react-frontend:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30     # un po’ di respiro
            periodSeconds: 10
            failureThreshold: 6         # 1 min prima di fallire

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60     # parte dopo 1 min
            periodSeconds: 20
            failureThreshold: 4


---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: wastevsion
spec:
  selector:
    app: react-frontend
  type: NodePort
  ports:
    - port: 80          # porta interna al cluster
      targetPort: 5000    # porta del container
      nodePort: 30080   # porta esterna sul nodo EC2
