apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: wastevsion
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      volumes:
      - name: ollama-storage
        hostPath:
          path: /home/ec2-user/WasteVision_-_Evaluation/WasteVision/ollama_mod/ollama2   # Update this path if needed
          type: DirectoryOrCreate
      initContainers:
      - name: model-downloader
        image: ollama/ollama:latest
        command: ["echo", "SONO NELL INIT"]
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama  # This path should match the main container's mountPath

      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_KEEP_ALIVE
          value: "24h"
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c" ]
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: wastevsion
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: NodePort
