apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: wastevsion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: raffa8/server:latest
          ports:
            - containerPort: 5001
          env:
            - name: JAEGER_AGENT_HOST
              value: "simplest-agent"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: GRPC_SERVER
              value: "jaeger-collector:14250"
          readinessProbe:
            httpGet:
              path: /     # Cambia se necessario
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /    # Cambia se necessario
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: wastevsion
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
