version: '3.8'
services:   
  react-frontend:
    build: ./react_frontend
    container_name: react-frontend 
    ports:
      - "5001:5000"
    networks:
      - backend
    depends_on:
      - server
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5001"
    volumes:
      - ./server/data:/app/data
    networks:
      - backend
  
  ollama:
    image: ollama/ollama:latest  
    container_name: ollama
    ports:
      - 7689:11434
    volumes:
      - ../../../../cloud/interfaccia_web/RagForCloudProject/ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=8  # Ottimizza l'esecuzione parallela su CPU
      - OLLAMA_THREADS=8  
    networks:
      - backend

  yolodetect:
    build: ./yolo
    ports:
      - "8091:8091"
    volumes:
      - ./yolo:/yolo
      - ./temp_images:/app/temp_images
    container_name: yolodetect
    networks:
      - backend


networks:
  backend:
    driver: bridge